# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F4

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0

beta_settings:
  cloud_sql_instances: sopra-fs26-group-21-server:europe-west6:sopra-fs26-db

env_variables:
  SPRING_PROFILES_ACTIVE: prod
  DB_PASSWORD: "REPLACE_ME_BEFORE_DEPLOY"
